/**
# Generated route files by rustgram route builder.

Please do not modify this file. Any changes will be overridden by the next route build.
Use the returned router instead
 */
use rustgram::{r, Router};

pub(crate) fn routes(router: &mut Router)
{
	router.post(
		"/api/v1/customer/register",
		r(crate::customer::customer_controller::register).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/prepare_login",
		r(crate::customer::customer_controller::prepare_login).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/done_login",
		r(crate::customer::customer_controller::done_login).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/validate_mfa",
		r(crate::customer::customer_controller::validate_mfa).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/validate_recovery_otp",
		r(crate::customer::customer_controller::validate_recovery_otp).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/verify_login",
		r(crate::customer::customer_controller::verify_login).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.get(
		"/api/v1/customer/captcha",
		r(crate::customer::customer_controller::customer_captcha).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer/password_reset",
		r(crate::customer::customer_controller::prepare_reset_password).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer/password_reset_validation",
		r(crate::customer::customer_controller::done_reset_password).add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer/refresh",
		r(crate::customer::customer_controller::refresh_jwt)
			.add(server_api_common::middleware::jwt::jwt_expire_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.post(
		"/api/v1/customer/register_validation",
		r(crate::customer::customer_controller::done_register)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.patch(
		"/api/v1/customer/email_resend",
		r(crate::customer::customer_controller::resend_email)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer",
		r(crate::customer::customer_controller::update)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer/data",
		r(crate::customer::customer_controller::update_data)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.put(
		"/api/v1/customer/password",
		r(crate::customer::customer_controller::change_password)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.delete(
		"/api/v1/customer",
		r(crate::customer::customer_controller::delete)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform)
			.add(server_api_common::middleware::app_token::app_token_base_app_transform),
	);
	router.patch(
		"/api/v1/customer/register_otp",
		r(crate::customer::customer_controller::register_otp).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.patch(
		"/api/v1/customer/reset_otp",
		r(crate::customer::customer_controller::reset_otp).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.patch(
		"/api/v1/customer/disable_otp",
		r(crate::customer::customer_controller::disable_otp).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/otp_recovery_keys",
		r(crate::customer::customer_controller::get_otp_recovery_keys).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.post(
		"/api/v1/customer/group",
		r(crate::customer::customer_controller::create_customer_group).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/group/all/:last_fetched_time/:last_id",
		r(crate::customer::customer_controller::get_groups).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/group/:group_id/invite/:invited_user",
		r(crate::customer::customer_controller::invite_customer_group_member)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/group/:group_id/update",
		r(crate::customer::customer_controller::update_group)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/group/:group_id",
		r(crate::customer::customer_controller::get_group)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/group/:group_id/member/:last_fetched_time/:last_user_id",
		r(crate::customer::customer_controller::get_group_member_list)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/group/:group_id/apps/:last_fetched_time/:last_app_id",
		r(crate::customer::customer_controller::get_all_apps_group)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.delete(
		"/api/v1/customer/group/:group_id",
		r(crate::customer::customer_controller::delete_customer_group)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/group/:group_id/change_rank",
		r(crate::customer::customer_controller::update_member)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.delete(
		"/api/v1/customer/group/:group_id/kick/:user_id",
		r(crate::customer::customer_controller::delete_group_user)
			.add(server_api_common::middleware::group::group_app_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/apps/:last_fetched_time/:last_app_id",
		r(crate::customer::customer_controller::get_all_apps).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.post(
		"/api/v1/customer/app",
		r(crate::customer_app::app_controller::create_app_user).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.post(
		"/api/v1/customer/app/:group_id",
		r(crate::customer_app::app_controller::create_app_group).add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/app/:app_id",
		r(crate::customer_app::app_controller::get_app_details)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/app/:app_id",
		r(crate::customer_app::app_controller::update)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/app/:app_id/options",
		r(crate::customer_app::app_controller::update_options)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/app/:app_id/file_options",
		r(crate::customer_app::app_controller::update_file_options)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.put(
		"/api/v1/customer/app/:app_id/group_options",
		r(crate::customer_app::app_controller::update_group_options)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.delete(
		"/api/v1/customer/app/:app_id",
		r(crate::customer_app::app_controller::delete)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.delete(
		"/api/v1/customer/app/:app_id/reset",
		r(crate::customer_app::app_controller::reset)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.patch(
		"/api/v1/customer/app/:app_id/token_renew",
		r(crate::customer_app::app_controller::renew_tokens)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.patch(
		"/api/v1/customer/app/:app_id/new_jwt_keys",
		r(crate::customer_app::app_controller::add_jwt_keys)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.get(
		"/api/v1/customer/app/:app_id/jwt",
		r(crate::customer_app::app_controller::get_jwt_details)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
	router.delete(
		"/api/v1/customer/app/:app_id/jwt/:jwt_id",
		r(crate::customer_app::app_controller::delete_jwt_keys)
			.add(crate::mw::app_access_transform)
			.add(server_api_common::middleware::jwt::jwt_customer_app_transform),
	);
}
